# data_fetcher.py
import pandas as pd
import os


def get_todays_schedule():
    """
    Reads the schedule generated by daily_scraper.py
    """
    if os.path.exists("todays_schedule.csv"):
        return pd.read_csv("todays_schedule.csv")
    else:
        # Fallback if you haven't run the scraper yet
        return pd.DataFrame([
            {"Home": "Run daily_scraper.py", "Away": "To See Schedule"}
        ])


def get_player_stats(team_name):
    """
    Reads player stats from the CSV generated by daily_scraper.py
    """
    if not os.path.exists("daily_stats.csv"):
        return pd.DataFrame()  # Return empty if no file

    df = pd.read_csv("daily_stats.csv")

    # Filter for the specific team
    team_stats = df[df['Team'] == team_name].copy()

    # Ensure columns exist for the model
    # Model expects: ['Last_5_Avg_FP', 'Opp_Def_Rank', 'Is_Home', 'Minutes_Avg']

    # Create missing columns if they don't exist in CSV
    if 'Opp_Def_Rank' not in team_stats.columns:
        team_stats['Opp_Def_Rank'] = 150  # Default middle rank

    return team_stats
